# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-13 14:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='дата действия')),
                ('action', models.CharField(choices=[('NEW', 'Создание'), ('EDIT', 'Редактирование'), ('DEL', 'Удаление')], max_length=10, verbose_name='тип действия')),
                ('obj_name', models.TextField(blank=True, verbose_name='наименование объекта')),
                ('obj_url', models.URLField(blank=True, verbose_name='ссылка на объект')),
                ('user', models.ForeignKey(default=main.current_user.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
