# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2018-03-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report_field',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', verbose_name='проект'),
        ),
    ]
